config:
  # List of Contracts that need to be monitored
  contracts:
    - name: "diaOracle"
      address: "0xD47FDf51D61c100C447E2D4747c7126F19fa23Ef"
      pathToArtifact: "artifacts/diaOracle.json"
      eventEmitted: "newCoinInfo"
      timestampVariable: "lastUpdateTimestamp"

    - name: "diaCoinGeckoOracle"
      address: "0x07E4120dD7411a49e091a20FA0be33a183C35d60"
      pathToArtifact: "artifacts/diaCoinGeckoOracle.json"
      eventEmitted: "OracleUpdate"
      timestampVariable: "timestamp"

  # Poll rate in seconds
  pollRate: 10
  # How far back to check if event has been emitted
  livenessRate: 86400
  # Url to the RPC/WS endpoint
  providerUrl: "https://eth-mainnet.alchemyapi.io/v2/_WOWR046h-XR_LYCIDupCSzlXsZrCt3i"
  # JsonRpcProvider / WebSocketProvider
  providerType: "JsonRpcProvider"
  # Etherscan API Key
  etherscanKey: "ZPFXKR715RF26Z3HYBIS5FZRWBERPVDHYT"
  # List of notifiers
  notifiers:
    - name: "email"
      emailId: "oracle.monitor@diadata.org"
      password: "password goes here"
      host: "gmail"
      to:
        - "jihaceh124@95ta.com"
      class: "EmailClient"
      successRate: 86400
    # You can add Slack, Discord, etc.
