config:
  # List of Contracts that need to be monitored
  contracts:
    - name: "diaOracle"
      address: "0xD47FDf51D61c100C447E2D4747c7126F19fa23Ef"
      pathToArtifact: "artifacts/diaOracle.json"
      eventEmitted: "newCoinInfo"
      timestampVariable: "lastUpdateTimestamp"

    - name: "diaCoinGeckoOracle"
      address: "0x07E4120dD7411a49e091a20FA0be33a183C35d60"
      pathToArtifact: "artifacts/diaCoinGeckoOracle.json"
      eventEmitted: "OracleUpdate"
      timestampVariable: "timestamp"

  # Poll rate in seconds
  pollRate: 10
  # How accurate should the timestamp be in seconds
  livenessRate: 86400
  # Url to the RPC/WS endpoint
  providerUrl: "https://mainnet.infura.io/v3/84842078b09946638c03157f83405213"
  # JsonRpcProvider / WebSocketProvider
  providerType: "JsonRpcProvider"
